### ISSUE TITLE
ValidateRedirectJwt (and Async) not working

### ISSUE THREAD

**Issue by christianz** [signicat/signicat-net#16]
**Note: For support questions, please visit [Signicat Community](https://community.signicat.com).**

* **I'm submitting a ...**
    - [X] bug report
    - [ ] feature request
    - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **What is the current behavior?**
Calling ValidateRedirectJwt or its async version returns an object that only has the Valid property filled out. This is because the JSON returned by the API is incorrectly formatted according to the serialization rules. See the JSON below, note I have REDACTED any identifying information.

```json
{
  "valid": true,
  "payload": {
    "AccountId": "REDACTED",
    "DocumentId": "REDACTED",
    "ExternalId": "REDACTED",
    "SignerId": "REDACTED",
    "ExternalSignerId": "REDACTED",
    "Error": null,
    "SignSuccess": {
      "SignatureMethodUniqueId": null,
      "FirstName": "REDACTED",
      "MiddleName": null,
      "LastName": "REDACTED",
      "FullName": "REDACTED, REDACTED",
      "DateOfBirth": null,
      "SignatureMethod": 14,
      "SignedTime": "2024-03-15T13:05:00Z",
      "Mechanism": 2
    },
    "Expires": "2024-03-15T13:15:01Z",
    "Aborted": null,
    "ClientIp": "REDACTED",
    "UserAgent": "REDACTED",
    "iss": "https://signapi-test.signicat.io"
  }
}
```

![image](https://github.com/signicat/signicat-net/assets/1029602/23a3b610-11de-4220-8a81-55a8f0b44b01)

* **If the current behavior is a bug, please provide the steps to reproduce**
I believe the easiest way is to run the ValidateRedirectJwt method on a valid idfy-jwt. Everything works as expected if the property names inside payload are camelCased (as defined in `Mapper.cs`).

* **What is the expected behavior?**
A fully populated object.

* **What is the motivation / use case for changing the behavior?**
-

* **Please tell us about your environment:**

    - Signicat SDK version: 1.6.0
    - .NET version: 4.8
    - OS version: Windows 11

* **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us
  to have context, etc)

Either change the property names in the resulting JSON to have lower-case first characters, or add [JsonPropertyName()] attributes above the properties inside "payload" and its child properties.

**Comment by Slettan** [comment]
Thanks for the bug report. This has been fixed in in `v1.7.1`.
